In [2]:
!pip install pandas numpy scikit-learn matplotlib seaborn flask ultralytics opencv-python streamlit

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (2.5.1)
Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: matplotlib in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (3.11.1)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting flask
  Using cached flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting ultralytics
  Using cached ultralytics-8.4.135-py3-none-any.whl.metadata (45 kB)
Collecting opencv-python
  Using cached opencv_python-5.0.0.93-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting streamlit
  Using cached streamlit-1.62.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.1-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Collecting blinker>=1.9.0 (from flask)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click>=8.1.3 (from flask)
  Using cached click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.2.0 (from flask)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from flask)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from flask)
  Using cached markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting werkzeug>=3.1.0 (from flask)
  Using cached werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Collecting filelock>=3.16.1 (from ultralytics)
  Using cached filelock-3.32.4-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: pyyaml>=5.3.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (2.34.2)
Collecting torch>=1.8.0 (from ultralytics)
  Using cached torch-2.13.0-cp314-cp314-win_amd64.whl.metadata (39 kB)
Collecting torchvision>=0.9.0 (from ultralytics)
  Using cached torchvision-0.28.0-cp314-cp314-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: psutil>=5.8.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (7.2.2)
Collecting polars>=0.20.0 (from ultralytics)
  Using cached polars-1.44.1-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py>=12.0.0 (from ultralytics)
  Using cached nvidia_ml_py-13.610.43-py3-none-any.whl.metadata (9.7 kB)
Collecting ultralytics-thop>=2.1.6 (from ultralytics)
  Using cached ultralytics_thop-2.1.6-py3-none-any.whl.metadata (13 kB)
Collecting ultralytics-platform>=0.1.3 (from ultralytics)
  Using cached ultralytics_platform-0.1.20-py3-none-any.whl.metadata (8.4 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=5.0.0 (from streamlit)
  Using cached altair-6.2.2-py3-none-any.whl.metadata (11 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=5.26.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (5.29.6)
Collecting pyarrow!=25.0.0,<26,>=7.0 (from streamlit)
  Using cached pyarrow-25.0.1-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (4.16.0)
Collecting starlette<2,>=0.46.0 (from streamlit)
  Using cached starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Collecting uvicorn<1,>=0.30.0 (from streamlit)
  Using cached uvicorn-0.52.4-py3-none-any.whl.metadata (6.6 kB)
Collecting httptools<1,>=0.6.3 (from streamlit)
  Using cached httptools-0.8.0-cp314-cp314-win_amd64.whl.metadata (3.7 kB)
Collecting anyio<5,>=4.0.0 (from streamlit)
  Using cached anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting python-multipart<1,>=0.0.10 (from streamlit)
  Using cached python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets<17,>=12.0.0 (from streamlit)
  Using cached websockets-16.1.1-cp314-cp314-win_amd64.whl.metadata (7.0 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: idna>=2.8 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from requests>=2.23.0->ultralytics) (3.5.0)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from requests>=2.23.0->ultralytics) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from requests>=2.23.0->ultralytics) (2026.7.22)
Collecting h11>=0.8 (from uvicorn<1,>=0.30.0->streamlit)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Collecting polars-runtime-32==1.44.1 (from polars>=0.20.0->ultralytics)
  Using cached polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: six>=1.5 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting setuptools>=77.0.3 (from torch>=1.8.0->ultralytics)
  Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=1.8.0->ultralytics)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.8.0->ultralytics)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting fsspec>=0.8.5 (from torch>=1.8.0->ultralytics)
  Using cached fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.8.0->ultralytics)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting httpx<1,>=0.28 (from ultralytics-platform>=0.1.3->ultralytics)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting httpcore==1.* (from httpx<1,>=0.28->ultralytics-platform>=0.1.3->ultralytics)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached flask-3.1.3-py3-none-any.whl (103 kB)
Using cached ultralytics-8.4.135-py3-none-any.whl (1.4 MB)
Using cached opencv_python-5.0.0.93-cp37-abi3-win_amd64.whl (44.0 MB)
Using cached streamlit-1.62.0-py3-none-any.whl (10.5 MB)
Using cached altair-6.2.2-py3-none-any.whl (797 kB)
Using cached anyio-4.14.2-py3-none-any.whl (125 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Using cached click-8.5.0-py3-none-any.whl (125 kB)
Using cached httptools-0.8.0-cp314-cp314-win_amd64.whl (92 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading pyarrow-25.0.1-cp314-cp314-win_amd64.whl (28.6 MB)
   ---------------------------------------- 0.0/28.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/28.6 MB ? eta -:--:--
   --- ------------------------------------ 2.4/28.6 MB 16.7 MB/s eta 0:00:02
   ------- -------------------------------- 5.5/28.6 MB 17.6 MB/s eta 0:00:02
   -------- ------------------------------- 6.3/28.6 MB 12.2 MB/s eta 0:00:02
   --------- ------------------------------ 7.1/28.6 MB 9.9 MB/s eta 0:00:03
   ----------- ---------------------------- 8.1/28.6 MB 8.3 MB/s eta 0:00:03
   ------------ --------------------------- 8.7/28.6 MB 7.7 MB/s eta 0:00:03
   ------------- -------------------------- 9.4/28.6 MB 7.1 MB/s eta 0:00:03
   -------------- ------------------------- 10.5/28.6 MB 6.6 MB/s eta 0:00:03
   --------------- ------------------------ 11.0/28.6 MB 6.2 MB/s eta 0:00:03
   ---------------- ----------------------- 11.8/28.6 MB 5.9 MB/s eta 0:00:03
   ----------------- ---------------------- 12.8/28.6 MB 5.8 MB/s eta 0:00:03
   ------------------ --------------------- 13.4/28.6 MB 5.5 MB/s eta 0:00:03
   ------------------- -------------------- 13.9/28.6 MB 5.4 MB/s eta 0:00:03
   -------------------- ------------------- 14.7/28.6 MB 5.2 MB/s eta 0:00:03
   --------------------- ------------------ 15.7/28.6 MB 5.1 MB/s eta 0:00:03
   ----------------------- ---------------- 16.8/28.6 MB 5.1 MB/s eta 0:00:03
   ------------------------ --------------- 17.3/28.6 MB 5.0 MB/s eta 0:00:03
   ------------------------ --------------- 17.8/28.6 MB 4.9 MB/s eta 0:00:03
   -------------------------- ------------- 18.6/28.6 MB 4.8 MB/s eta 0:00:03
   --------------------------- ------------ 19.4/28.6 MB 4.8 MB/s eta 0:00:02
   ---------------------------- ----------- 20.4/28.6 MB 4.8 MB/s eta 0:00:02
   ----------------------------- ---------- 21.2/28.6 MB 4.8 MB/s eta 0:00:02
   ------------------------------ --------- 22.0/28.6 MB 4.6 MB/s eta 0:00:02
   ------------------------------- -------- 22.5/28.6 MB 4.6 MB/s eta 0:00:02
   -------------------------------- ------- 23.3/28.6 MB 4.6 MB/s eta 0:00:02
   ---------------------------------- ----- 24.4/28.6 MB 4.6 MB/s eta 0:00:01
   ----------------------------------- ---- 25.2/28.6 MB 4.5 MB/s eta 0:00:01
   ----------------------------------- ---- 25.7/28.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 26.5/28.6 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 27.5/28.6 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  28.3/28.6 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 28.6/28.6 MB 4.4 MB/s  0:00:06
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ---------------------------------------- 0.0/11.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.4 MB 3.8 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/11.4 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.4 MB 4.0 MB/s eta 0:00:03
   ----------- ---------------------------- 3.4/11.4 MB 4.2 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.4 MB 4.2 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.4 MB 4.3 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.4 MB 4.3 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.4 MB 4.1 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.4 MB 4.0 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.4 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.4 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.4 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.4 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.4 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 11.4/11.4 MB 3.9 MB/s  0:00:02
Downloading python_multipart-0.0.32-py3-none-any.whl (30 kB)
Using cached starlette-1.6.0-py3-none-any.whl (75 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached uvicorn-0.52.4-py3-none-any.whl (79 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading websockets-16.1.1-cp314-cp314-win_amd64.whl (179 kB)
Downloading filelock-3.32.4-py3-none-any.whl (99 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl (15 kB)
Downloading narwhals-2.25.0-py3-none-any.whl (467 kB)
Downloading nvidia_ml_py-13.610.43-py3-none-any.whl (53 kB)
Downloading polars-1.44.1-py3-none-any.whl (865 kB)
   ---------------------------------------- 0.0/865.2 kB ? eta -:--:--
   ------------------------ --------------- 524.3/865.2 kB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 865.2/865.2 kB 3.6 MB/s  0:00:00
Downloading polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl (53.7 MB)
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
    --------------------------------------- 0.8/53.7 MB 4.7 MB/s eta 0:00:12
   - -------------------------------------- 2.1/53.7 MB 5.5 MB/s eta 0:00:10
   -- ------------------------------------- 3.4/53.7 MB 5.7 MB/s eta 0:00:09
   --- ------------------------------------ 4.5/53.7 MB 5.9 MB/s eta 0:00:09
   ---- ----------------------------------- 5.8/53.7 MB 5.7 MB/s eta 0:00:09
   ----- ---------------------------------- 7.3/53.7 MB 6.1 MB/s eta 0:00:08
   ------ --------------------------------- 8.7/53.7 MB 6.2 MB/s eta 0:00:08
   ------- -------------------------------- 9.4/53.7 MB 5.9 MB/s eta 0:00:08
   ------- -------------------------------- 10.2/53.7 MB 5.6 MB/s eta 0:00:08
   -------- ------------------------------- 11.0/53.7 MB 5.4 MB/s eta 0:00:08
   -------- ------------------------------- 11.8/53.7 MB 5.2 MB/s eta 0:00:09
   --------- ------------------------------ 12.3/53.7 MB 5.1 MB/s eta 0:00:09
   --------- ------------------------------ 13.4/53.7 MB 5.0 MB/s eta 0:00:09
   ---------- ----------------------------- 14.2/53.7 MB 4.9 MB/s eta 0:00:09
   ----------- ---------------------------- 14.9/53.7 MB 4.8 MB/s eta 0:00:09
   ----------- ---------------------------- 15.7/53.7 MB 4.8 MB/s eta 0:00:08
   ------------ --------------------------- 16.5/53.7 MB 4.7 MB/s eta 0:00:08
   ------------ --------------------------- 17.3/53.7 MB 4.7 MB/s eta 0:00:08
   ------------- -------------------------- 18.1/53.7 MB 4.6 MB/s eta 0:00:08
   -------------- ------------------------- 18.9/53.7 MB 4.6 MB/s eta 0:00:08
   -------------- ------------------------- 19.4/53.7 MB 4.5 MB/s eta 0:00:08
   --------------- ------------------------ 20.4/53.7 MB 4.5 MB/s eta 0:00:08
   --------------- ------------------------ 21.2/53.7 MB 4.5 MB/s eta 0:00:08
   ---------------- ----------------------- 21.8/53.7 MB 4.5 MB/s eta 0:00:08
   ---------------- ----------------------- 22.5/53.7 MB 4.4 MB/s eta 0:00:08
   ----------------- ---------------------- 23.6/53.7 MB 4.4 MB/s eta 0:00:07
   ----------------- ---------------------- 24.1/53.7 MB 4.4 MB/s eta 0:00:07
   ------------------ --------------------- 25.2/53.7 MB 4.3 MB/s eta 0:00:07
   ------------------- -------------------- 25.7/53.7 MB 4.3 MB/s eta 0:00:07
   ------------------- -------------------- 26.5/53.7 MB 4.3 MB/s eta 0:00:07
   -------------------- ------------------- 27.3/53.7 MB 4.3 MB/s eta 0:00:07
   -------------------- ------------------- 28.0/53.7 MB 4.3 MB/s eta 0:00:06
   --------------------- ------------------ 28.8/53.7 MB 4.2 MB/s eta 0:00:06
   ---------------------- ----------------- 29.6/53.7 MB 4.2 MB/s eta 0:00:06
   ---------------------- ----------------- 30.4/53.7 MB 4.2 MB/s eta 0:00:06
   ----------------------- ---------------- 31.2/53.7 MB 4.2 MB/s eta 0:00:06
   ----------------------- ---------------- 32.0/53.7 MB 4.2 MB/s eta 0:00:06
   ------------------------ --------------- 32.8/53.7 MB 4.2 MB/s eta 0:00:05
   ------------------------ --------------- 33.6/53.7 MB 4.2 MB/s eta 0:00:05
   ------------------------- -------------- 34.3/53.7 MB 4.2 MB/s eta 0:00:05
   -------------------------- ------------- 35.1/53.7 MB 4.2 MB/s eta 0:00:05
   -------------------------- ------------- 35.9/53.7 MB 4.2 MB/s eta 0:00:05
   --------------------------- ------------ 36.7/53.7 MB 4.1 MB/s eta 0:00:05
   --------------------------- ------------ 37.5/53.7 MB 4.1 MB/s eta 0:00:04
   ---------------------------- ----------- 38.3/53.7 MB 4.1 MB/s eta 0:00:04
   ----------------------------- ---------- 39.1/53.7 MB 4.1 MB/s eta 0:00:04
   ----------------------------- ---------- 39.8/53.7 MB 4.1 MB/s eta 0:00:04
   ------------------------------ --------- 40.6/53.7 MB 4.1 MB/s eta 0:00:04
   ------------------------------ --------- 41.4/53.7 MB 4.1 MB/s eta 0:00:03
   ------------------------------- -------- 42.2/53.7 MB 4.1 MB/s eta 0:00:03
   -------------------------------- ------- 43.0/53.7 MB 4.1 MB/s eta 0:00:03
   -------------------------------- ------- 43.5/53.7 MB 4.1 MB/s eta 0:00:03
   --------------------------------- ------ 44.6/53.7 MB 4.1 MB/s eta 0:00:03
   --------------------------------- ------ 45.1/53.7 MB 4.1 MB/s eta 0:00:03
   ---------------------------------- ----- 46.1/53.7 MB 4.1 MB/s eta 0:00:02
   ---------------------------------- ----- 46.9/53.7 MB 4.1 MB/s eta 0:00:02
   ----------------------------------- ---- 47.7/53.7 MB 4.0 MB/s eta 0:00:02
   ------------------------------------ --- 48.5/53.7 MB 4.0 MB/s eta 0:00:02
   ------------------------------------ --- 49.0/53.7 MB 4.0 MB/s eta 0:00:02
   ------------------------------------- -- 49.8/53.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 50.6/53.7 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 51.4/53.7 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 52.2/53.7 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  53.0/53.7 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  53.5/53.7 MB 4.0 MB/s eta 0:00:01

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import cv2
import flask
import streamlit
from ultralytics import YOLO

Creating new Ultralytics Settings v0.0.8 file
View Ultralytics Settings with 'yolo settings' or at 'C:\Users\ujwal\AppData\Roaming\Ultralytics\settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart#ultralytics-settings.

In [ ]:
df = pd.read_csv('dataset_traffic_accident_prediction1.csv')  
print(df.shape) 
print(df.columns.tolist()) 
df.head()

(840, 14)
['Weather', 'Road_Type', 'Time_of_Day', 'Traffic_Density', 'Speed_Limit', 'Number_of_Vehicles', 'Driver_Alcohol', 'Accident_Severity', 'Road_Condition', 'Vehicle_Type', 'Driver_Age', 'Driver_Experience', 'Road_Light_Condition', 'Accident']

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition,Accident
0,Rainy,City Road,Morning,1.0,100.0,5.0,0.0,NaN,Wet,Car,51.0,48.0,Artificial Light,0.0
1,Clear,Rural Road,Night,NaN,120.0,3.0,0.0,Moderate,Wet,Truck,49.0,43.0,Artificial Light,0.0
2,Rainy,Highway,Evening,1.0,60.0,4.0,0.0,Low,Icy,Car,54.0,52.0,Artificial Light,0.0
3,Clear,City Road,Afternoon,2.0,60.0,3.0,0.0,Low,Under Construction,Bus,34.0,31.0,Daylight,0.0
4,Rainy,Highway,Morning,1.0,195.0,11.0,0.0,Low,Dry,Car,62.0,55.0,Artificial Light,1.0

In [ ]:
print(df['Accident'].value_counts()) 
print(df['Accident'].value_counts(normalize=True) * 100)

Accident
0.0    559
1.0    239
Name: count, dtype: int64
Accident
0.0    70.050125
1.0    29.949875
Name: proportion, dtype: float64

In [ ]:
print(df.isnull().sum())

Weather                 42
Road_Type               42
Time_of_Day             42
Traffic_Density         42
Speed_Limit             42
Number_of_Vehicles      42
Driver_Alcohol          42
Accident_Severity       42
Road_Condition          42
Vehicle_Type            42
Driver_Age              42
Driver_Experience       42
Road_Light_Condition    42
Accident                42
dtype: int64

In [ ]:
print(df[df.isnull().all(axis=1)].shape)

(0, 14)

In [8]:
print(df[df.isnull().any(axis=1)].shape)

(435, 14)

In [9]:
df = df.dropna(subset=['Accident'])
print(df.shape)

(798, 14)

In [10]:
print(df.isnull().sum())

Weather                 40
Road_Type               40
Time_of_Day             38
Traffic_Density         40
Speed_Limit             41
Number_of_Vehicles      38
Driver_Alcohol          40
Accident_Severity       42
Road_Condition          41
Vehicle_Type            39
Driver_Age              40
Driver_Experience       41
Road_Light_Condition    40
Accident                 0
dtype: int64

In [11]:
# Numeric columns → fill missing values with median
numeric_cols = ['Traffic_Density', 'Speed_Limit', 'Number_of_Vehicles', 'Driver_Age', 'Driver_Experience']
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns → fill missing values with mode (most frequent value)
categorical_cols = ['Weather', 'Road_Type', 'Time_of_Day', 'Driver_Alcohol', 'Road_Condition', 'Vehicle_Type', 'Road_Light_Condition']
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print(df.isnull().sum())

Weather                  0
Road_Type                0
Time_of_Day              0
Traffic_Density          0
Speed_Limit              0
Number_of_Vehicles       0
Driver_Alcohol           0
Accident_Severity       42
Road_Condition           0
Vehicle_Type             0
Driver_Age               0
Driver_Experience        0
Road_Light_Condition     0
Accident                 0
dtype: int64

In [12]:
categorical_cols = ['Weather', 'Road_Type', 'Time_of_Day', 'Driver_Alcohol', 'Road_Condition', 'Vehicle_Type', 'Road_Light_Condition']

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print(df_encoded.shape)
df_encoded.head()

(798, 26)

,Traffic_Density,Speed_Limit,Number_of_Vehicles,Accident_Severity,Driver_Age,Driver_Experience,Accident,Weather_Foggy,Weather_Rainy,Weather_Snowy,...,Time_of_Day_Night,Driver_Alcohol_1.0,Road_Condition_Icy,Road_Condition_Under Construction,Road_Condition_Wet,Vehicle_Type_Car,Vehicle_Type_Motorcycle,Vehicle_Type_Truck,Road_Light_Condition_Daylight,Road_Light_Condition_No Light
0,1.0,100.0,5.0,NaN,51.0,48.0,0.0,False,True,False,...,False,False,False,False,True,True,False,False,False,False
1,1.0,120.0,3.0,Moderate,49.0,43.0,0.0,False,False,False,...,True,False,False,False,True,False,False,True,False,False
2,1.0,60.0,4.0,Low,54.0,52.0,0.0,False,True,False,...,False,False,True,False,False,True,False,False,False,False
3,2.0,60.0,3.0,Low,34.0,31.0,0.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,1.0,195.0,11.0,Low,62.0,55.0,1.0,False,True,False,...,False,False,False,False,False,True,False,False,False,False